language: go
go:
  - 1.4
  - tip
env:
  - GOARCH=386
  - GOARCH=amd64
before_install:
  - sed -ie 's;git://;https://;' .git/config
install:
  - go get -d -t -f
script:
  - go test
services:
  - mongodb
