language: go
sudo: false
go:
  - 1.4.2
  - 1.5.2
  - 1.6beta1
  - tip
env:
  - GOARCH=386
  - GOARCH=amd64
before_install:
  - sed -ie 's;git://;https://;' .git/config
install:
  - go get -d -t
script:
  - go test
services:
  - mongodb
